//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentEquipment.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassportClient
    {
        public int IDPassportClient { get; set; }
        public int IDClient { get; set; }
        public int IDPassport { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Passport Passport { get; set; }
    }
}
