//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentEquipment.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rentList
    {
        public int ID { get; set; }
        public string FIOClient { get; set; }
        public string FIOEmployee { get; set; }
        public string Product { get; set; }
        public System.DateTime TimeRent { get; set; }
        public System.DateTime TimeRentEnd { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string tagDeadline { get; set; }
    }
}
